# Generated by Django 6.0.3 on 2026-04-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, default='default/dealer.png', max_length=255, null=True, verbose_name='Аватар'),
        ),
    ]
