# Generated by Django 6.0.3 on 2026-04-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_description_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='image_path',
        ),
    ]
